<Project Sdk="MSTest.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>NeNeCommander.Domain.Tests</RootNamespace>
    <AssemblyName>NeNeCommander.Domain.Tests</AssemblyName>
    <TestingExtensionsProfile>Default</TestingExtensionsProfile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/NeNeCommander.Domain/NeNeCommander.Domain.csproj" />
  </ItemGroup>
</Project>
