namespace NeNeCommander.Presentation.WinUI.Input;

/// <summary>Represents whether a key event is initial or generated by auto-repeat.</summary>
public abstract record KeyRepeatState
{
    /// <summary>Gets the initial key-press state.</summary>
    public static KeyRepeatState Initial { get; } = new InitialState();

    /// <summary>Gets the auto-repeat state.</summary>
    public static KeyRepeatState Repeated { get; } = new RepeatedState();

    private KeyRepeatState()
    {
    }

    private sealed record InitialState : KeyRepeatState;
    private sealed record RepeatedState : KeyRepeatState;
}
